[general]
caption_extension = ".txt"
keep_tokens = 1

[[datasets]]
resolution = 1024
batch_size = 2
enable_bucket = true
bucket_no_upscale = true
min_bucket_reso = 512
max_bucket_reso = 1536
bucket_reso_steps = 64

  [[datasets.subsets]]
  image_dir = ""
  num_repeats = 10
  keep_tokens = 1
  flip_aug = false
  caption_prefix = ""
  shuffle_caption = false
  caption_tag_dropout_rate = 0.0
  caption_dropout_rate = 0.05
  caption_dropout_every_n_epochs = 0
